<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function CommentsByPost($id) {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.post = :post_id')
            ->orderBy('u.created')
            ->setParameter('post_id', $id);

        return $qb->getQuery()->getResult();
    }


}
