services:

  tag.form.type.tags:
      class: JB\TagBundle\Form\Type\TagsType
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
        - { name: form.type}

#    tag.example:
#        class: JB\TagBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
