<?php

namespace JB\TagBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use JB\TagBundle\Entity\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($q){
        return $this->createQueryBuilder('t')
            ->where('t.name like :search')
            ->setParameter('search', "%".$q."%")
            ->getQuery()
            ->getResult();
    }

    public function findUnused($class){

        $em = $this->getEntityManager();
        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata(Tag::class, 't');

        return $em->createNativeQuery('
        select t.id, t.name 
        from tag t
        left join post_tag on post_tag.tag_id = t.id
        where post_tag.tag_id is null
        ', $rsm)
            ->getResult();

    }
}
